default: &default
  split_design_documents_per_view: false
  default_language: :javascript

development:
  <<: *default
  database: blog_develop
test:
  <<: *default
  database: blog_develop
production:
  <<: *default
  database: blog_develop